spring:
  application:
    name: matmatikk-api
  # DB
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:matmatikk-api
    username: sa
    password: password
  # Prefill
prefill: true

# Security
jwt:
  key: ${JWT_KEY}
  access-token-expiration: 3600000
  refresh-token-expiration: 86400000
