CREATE TABLE IF NOT EXISTS USERS
(
    ID         VARCHAR(36) PRIMARY KEY,
    FIRST_NAME VARCHAR NOT NULL,
    LAST_NAME  VARCHAR NOT NULL,
    EMAIL      VARCHAR NOT NULL,
    PASSWORD   VARCHAR NOT NULL,
    ROLE       VARCHAR NOT NULL
);
